<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN2070121W2" ignored="0" name="Retry failed Test Cases" tests="8" failures="2" timestamp="02 Jul 2018 10:33:38 GMT" time="0.146" errors="0">
  <testcase name="testcase1" time="0.022" classname="mytest.MyTest">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.007" classname="mytest.MyTest">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.002" classname="mytest.MyTest">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.002" classname="mytest.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytest.MyTest.testcase1(MyTest.java:12)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase2" time="0.004" classname="mytest.MyTest">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.001" classname="mytest.MyTest">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.002" classname="mytest.MyTest">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.004" classname="mytest.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytest.MyTest.testcase2(MyTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- Retry failed Test Cases -->
